### ISSUE TITLE
Add the i386 and amd64 MSI files in the Assets section of github releases

### ISSUE THREAD

**Issue by vincentremond** [springcomp/optimized-azerty-win#100]
I am creating a new chocolatey package to install quicly your layout on my new computers/virtual machines.

It would be much easier to automate if I could download directly the i386 and amd64 from the assets sections of the releases on Github.

For the moment I have to extract the MSI files from the `Setup.zip` file.

**Comment by springcomp** [comment]
Thank you for your feedback.

I will try and address this as time permits.

For anyone willing to help, PRs are welcome.
The way to do it is probably to add a new artifact as part of the AppVeyor build, therefore, producing:

- setup.zip as currently.
- KBFRZ71_i386.msi.
- KBFRZ71_amd64.msi.

**Comment by vincentremond** [comment]
Here is the PR :
https://github.com/springcomp/optimized-azerty-win/pull/102

And here is the chocolatey package sources :
https://github.com/vincentremond/chocolatey-azerty-nf-z71-300

And the chocolatey package is here :
https://chocolatey.org/packages/azerty-nf-z71-300/1.7.0.0
