### ISSUE TITLE
Le cédille minuscule ne fonctionne pas

### ISSUE THREAD

**Issue by Aymkdn** [springcomp/optimized-azerty-win#101]
Bonjour,

J'ai acheté un clavier LDLC Azerty+. et j'ai remarqué que le « ç » (minuscule) ne fonctionne pas (alors que le « Ç » majuscule fonctionne).

Une idée de pourquoi ?

Je suis sous Windows 10 Version 10.0.18363 Build 18363

Merci

**Comment by springcomp** [comment]
Bonjour, merci pour votre retour.

Quelle [version du pilote](https://github.com/springcomp/optimized-azerty-win/wiki/FAQ#which-version) avez-vous, s’il vous plait ?

**Comment by springcomp** [comment]
En attendant, vous pouvez toujours vous en sortir avec la frappe de <kbd>AltGr</kbd>+<kbd>v</kbd>, <kbd>c</kbd>.

**Comment by Aymkdn** [comment]
Merci pour la réponse rapide !

Alors, j'utilisais la version fournie par LDLC (v1.4.0). J'ai mis à jour vers 1.7.0 mais j'avais le même problème… du coup, j'ai cherché si je n'avais pas un programme qui capturait ma commande, et ta suggestion de <kbd>AltGr</kbd>+ <kbd>v</kbd> m'a montré qu'effectivement un programme ("John's Background Switcher") était à l'origine du problème. Après l'avoir modifié, tout fonctionne !

Il faut maintenant que je m'habitue à la nouvelle disposition des touches... pas évident, en particulier quand on est un programmeur !

Merci :-)
