### ISSUE TITLE
"Paste format only" broken in Google Sheet

### ISSUE THREAD

**Issue by vincentremond** [springcomp/optimized-azerty-win#104]
In Google Sheet the shortcut `Ctrl`+`Alt`+`V` doesn't work anymore with the Azerty+ layout.

It works fine with Windows' default Azerty layout.

**Comment by springcomp** [comment]
Yes, you are right, good catch!

Unfortunately, I don’t think there’s much that I can do about this.

<kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>v</kbd> is, _in fact_, <kbd>AltGr</kbd>+<kbd>v</kbd> which is a dead-key that maps to the `¸` (COMBINING CEDILLA U+0327) diacritical.

In fact, if you type <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>v</kbd>, followed by <kbd>Space</kbd> in Google Sheets, you will observe that a `¸` (CEDILLA U+00B8) character is typed into a cell.

Instead, I have initiated a new page listing the [known broken keyboard shortcuts](https://github.com/springcomp/optimized-azerty-win/wiki/Known-Broken-Keyboard-Shortcuts) when using the new AZERTY-NF layout.

**Comment by vincentremond** [comment]
Ok not fixable :)
