### ISSUE TITLE
[Windows 7] Applications randomly switching back to AZERTY

### ISSUE THREAD

**Issue by xDEADC0DE** [springcomp/optimized-azerty-win#105]
I have a weird issue with the driver on Windows 7: Seemingly at random, an application will switch back to the AZERTY layout, while the rest of the apps keep using the correct layout.
This is solved by restarting the application.

Has anyone else experienced this? 

This seems to only happen on Windows 7, I also use the driver on a Windows 10 machine and never had this issue.

**Comment by springcomp** [comment]
Hello, thank you for your feedback.

I have not extensive experience of the driver on Windows 7 unfortunately.
Perhaps other users will provide feedback.

**Comment by xDEADC0DE** [comment]
Thanks. It’s such a weird bug (why would it affect a single app?) that it could be caused a million different things.

But if it is caused by Windows 7, hopefully someone else experiencing this issue will come accross this page.

**Comment by ClavierPixelKey** [comment]
This might not be specifically a Windows 7 issue, but an input method shortcut that should be disabled.

[https://github.com/springcomp/optimized-azerty-win/issues/98](url)

**Comment by xDEADC0DE** [comment]
I thought about that, but why would it only affect a single application at a time ?
Could be some shortcut specific to those apps, but they are quite distinct: at the moment this issue as appeared on Chrome, Eclipse, and SublimeText 3

**Comment by xDEADC0DE** [comment]
As I said before, this isn’t a big issue (and could be caused by something other than the driver), but maybe someone else experiencing it will find this page.

Is there anything I could check when/if the problem reappears, to help identify the cause?

**Comment by xDEADC0DE** [comment]
This used to happen once every few days, but feels much more frequent now. I’ve had this issue multiple times in the last few hours :O

**Comment by xDEADC0DE** [comment]
> [#98](https://github.com/springcomp/optimized-azerty-win/issues/98)

Oh! I hadn't noticed the linked issue! It does sound very similar, appart from the Windows version…

**Comment by xDEADC0DE** [comment]
OMG I figured it out!

It was good old “Ctrl+Shift”, which switches keyboard layouts in the same language… Apparently on Windows 7 the layout changes *per application* :scream: !!

I disabled that shortcut, and configured windows to show the language bar, so hopefully I won’t have this issue anymore :laughing:
