### ISSUE TITLE
AFNOR Keyboard - bug with : ;

### ISSUE THREAD

**Issue by FrancoisNarolles** [springcomp/optimized-azerty-win#106]
deleted.

**Comment by springcomp** [comment]
Please, feel free to ask any question.

**Comment by FrancoisNarolles** [comment]
Bonjour et merci
J'avais un souci avec le mauvais pilote. Je n'avais pas pris le temps de rebooter après l'installation de la bonne version. Tout est rentré dans l'ordre !
Merci

**Comment by springcomp** [comment]
Je suis heureux que vous utilisiez la disposition. J'espère qu'elle vous donnera toute satisfaction.
