### ISSUE TITLE
Unicode characters in Windows password -> account locked out

### ISSUE THREAD

**Issue by pieter-degroote** [springcomp/optimized-azerty-win#107]
When using additional keyboard layouts, the use of Unicode characters higher than "**Basic Latin**" in the Windows password can cause being **locked out of your account**.

This can happen especially in cases where you uninstall a keyboard layout, perform a restart, and try update to the latest version. In this case you might be stuck at the login screen after that restart, where you have another keyboard layout and are not able to add a new layout.

A letter like 'ë' can also be typed as Alt + 0235, but a letters like 'ź' and 'ẞ' (capital Eszett) cannot be typed as an Alt code at the login screen.

The only 'cure' is to use only "Basic Latin" characters (codes 32 to 126) for a Windows password, as this is an issue of the Windows OS itself.

(In Linux, there is the exact same problem. See also [this post](https://github.com/pieter-degroote/UltimateKEYS/issues/3).)

**Comment by springcomp** [comment]
Hi @pieter-degroote  thank you for your feedback.
Yes, indeed you are completely right.

However, this is not an issue from this keyboard layout, or any keyboard layout in particular indeed 🤷‍♂️.

Thanks for your feedback.
