### ISSUE TITLE
I can't install the keyboard using the setup.exe

### ISSUE THREAD

**Issue by OscarSenlis** [springcomp/optimized-azerty-win#108]
After a while the setup.exe gives me an error : installer is no longer reponding.
What should I do ?

**Comment by springcomp** [comment]
I thanks for the feedback and sorry for the issue.
What version of Windows are you using?

**Comment by OscarSenlis** [comment]
I am using windows 10. However I noticed I had similar issues with msi file on my computer.

**Comment by OscarSenlis** [comment]
Is turns out it was a windows registry issue.
