### ISSUE TITLE
Just wanted to say thanks

### ISSUE THREAD

**Issue by Slion** [springcomp/optimized-azerty-win#110]
Guys, this is awesome! I just wanted to say thanks for sharing this. I really like our new AZERTY keyboard layout. Just converted one of my keyboards, three to go.

![image](https://user-images.githubusercontent.com/6508892/112393558-8fab9a00-8cfb-11eb-8646-f7482f0df1b0.png)

**Comment by springcomp** [comment]
That’s a great piece of feedback 😄.
Thank you very much.

**Comment by Slion** [comment]
Merci encore! Je commence juste à l’utiliser mais je l’adore déjà l’AZERTY amélioré. Tout fonctionne super bien avec votre pilote. Les modes sont très pratiques pour accéder aux caractères Grecques notamment. Savez vous si l’adoption progresse chez les fabriquant de matériel et de logiciel. Sans doute pas vraiment étant donné que Microsoft ne le supporte toujours pas par défaut apparemment.

**Comment by Slion** [comment]
Je viens de regarder sur le site de Lenovo et il ne l’offre toujours pas, incompréhensible…
J’adore les points de suspension aussi😃

**Comment by springcomp** [comment]
> Merci encore! Je commence juste à l’utiliser mais je l’adore déjà l’AZERTY amélioré. Tout fonctionne super bien avec votre pilote. Les modes sont très pratiques pour accéder aux caractères Grecques notamment. Savez vous si l’adoption progresse chez les fabricants de matériel et de logiciel. Sans doute pas vraiment étant donné que Microsoft ne le supporte toujours pas par défaut apparemment.

Malheureusement, non, pas beaucoup.
Il était question à l'origine que les administrations soient encouragées à utiliser la nouvelle disposition. Je pense que si les écoles et les universités en étaient pourvues, Il y aurait une chance qu'elle soit adoptée plus largement.

LDLC propose courageusement un modèle qui n'est pas très onéreux.

Mes changements favoris sont les signes de ponctuation en accès direct, les caractères <kbd>+</kbd> et <kbd>-</kbd> qui permettent maintenant de zoomer dans de nombreuses applications (avec la touche <kbd>Ctrl</kbd>), et enfin les majuscules accentuées.

Merci pour vos encouragements.

**Comment by Slion** [comment]
> les caractères + et - qui permettent maintenant de zoomer dans de nombreuses applications

Très bon point c’est vrai. Je viens de mettre à jour ma proposition pour le clavier du [FxTec Pro1X](https://community.fxtec.com/topic/2318-azerty-layout-proposal/) en conséquence. C’est un smartphone avec clavier mais il lui manque une touche pour pouvoir faire un AZERTY presque complet. J’avais donc combiné le - et le + sur la même touche mais c’était une mauvaise idée.

Oui les ponctuations, les accents, les barres obliques tout est amélioré, pour le code, pour écrire en Allemand et autre langue européenne c’est aussi tellement mieux.

**Comment by Slion** [comment]
Y a un truc de pas terrible c’est que pour obtenir 0.5 sans pavé numérique je dois taper cinq touches au lieux de quatre, c’est un peu la gymnastique avec le shift là, mais bon je devrais y survivre 😁

**Comment by springcomp** [comment]
Alors, tu peux installer la version "AZERTY-NF (Numérique)" spécialement pour les laptops.
Il permet de faire fonctionner <kbd>Caps Lock</kbd> de manière [strictement normalisée](https://springcomp.github.io/optimized-azerty-win/#sgcaps).

![image](https://user-images.githubusercontent.com/8488398/112655648-e70f4e80-8e50-11eb-9799-f16bf16c9934.png)

**Comment by Slion** [comment]
Oui, j’y songe, c’est sans doute mieux pour la saisie de chiffre mais pour taper du code avec juste un chiffre de temps en temps c’est la même chose, cinq touche pour 0.5 – juste un peu moins de gymnastique avec la touche shift mais bon pas vraiment mieux non plus.

**Comment by Slion** [comment]
Est-ce possible de faire les exposants? Si non ce serait bien de les ajouter dans le mode des charactères Grecques par exemples.
¹ ² ³

**Comment by springcomp** [comment]
> Est-ce possible de faire les exposants? Si non ce serait bien de les ajouter dans le mode des charactères Grecques par exemples.
> ¹ ² ³

Oui, bien sûr. Circonflexe (<kbd>^</kbd>), suivi du chiffre.
De même pour les indices, Caron (<kbd>AltGr</kbd>+<kbd>^</kbd>) suivi du chiffre.

Fonctionne également avec les signes +, -, = et les parenthèses.

**Comment by springcomp** [comment]
Je t'invite à consulter [la documentation](https://springcomp.github.io/optimized-azerty-win/).

Je suis particulièrement fier de supporter les caractères diacritiques combinants. Par exemple, le c-cédille-accent aigu 🤷‍♂️ Et tant d'autres...

**Comment by Slion** [comment]
Trés impressionant! Encore une question: sais tu si il existe un tel pilote pour Android?

**Comment by Slion** [comment]
> Gabarit vectoriel pour le logiciel Inkscape
Le lien du gabarit vectoriel ne fonctionne pas.

**Comment by Slion** [comment]
> Oui, bien sûr. Circonflexe (^), suivi du chiffre.
De même pour les indices, Caron (AltGr+^) suivi du chiffre.

Par curiosité, cela fait-il partie de la norme ou est-ce une addition?

**Comment by springcomp** [comment]
Les indices et les exposants sont normalisés. J'y ai ajouté les signes, +, -, =, et les parenthèses.

**Comment by springcomp** [comment]
> Trés impressionant! Encore une question: sais tu si il existe un tel pilote pour Android?

À ma connaissance, non.

**Comment by springcomp** [comment]
> > Gabarit vectoriel pour le logiciel Inkscape
> 
> Le lien du gabarit vectoriel ne fonctionne pas.

Corrigé ! Merci 👍.
