### ISSUE TITLE
Problème avec Keyboard Layout Creator

### ISSUE THREAD

**Issue by d0ob** [springcomp/optimized-azerty-win#111]
Bonjour,

Edit : J’aurai finalement recréé un clavier semblable de zéro, il sera certes rudimentaire, mais bien suffisant pour mon usage. Le souci persistant, mais ayant fait avec, je clos cette issue.
__

J’aurais aimé changer quelques touches, le seul moyen que j’ai trouvé est «Keyboard Layout Creator», seulement je n’arrive à ouvrir aucun AZERTY+ avec : En les chargeant directement depuis mes claviers ils ne s’ouvrent pas du tout, sans log d’erreur, et si je peux en revanche ouvrir directement un fichier source, cette fois je ne pourrai pas le sauvegarder. ( Ceci-dit j’ai bien un log cette fois : https://pastebin.com/YGBKdM9C )

Puis-je contourner ce problème ? Ou aurais-je un autre moyen pour faire ces quelques modifications ? J’ai cherché comme j’ai pu sur le site dédié à l’AZERTY+ mais n’ai pas trouvé ma réponse, ni sur internet.
__

_D’ailleurs, à propos du site, les autocollants proposés sur cette page, ( http://norme-azerty.fr/#setup ) sous votre pseudo, renvoient maintenant vers un 404. J’ai envoyé un mail au contact, car sans trouver à vous joindre, je n’osais pas commenter sans raison valable sur un de vos répertoires GitHub, mais maintenant que je suis là…_
__

**Un grand merci en tout cas, j’aurai bien de labeur à me familiariser au bépo, je ne sais pas en combien de semaines il faudra compter ; Mais en revanche je me suis déjà bien habitué à cet AZERTY+ ! Quelle agréabilité, ça change la vie !**

**Comment by springcomp** [comment]
Bonjour @d0ob  merci pour votre commentaire.

Que souhaitez-vous proposer comme modifications ?

Si vous êtes familier avec les outils de développement, il vous est tout à fait possible de proposer une modification du code source et de proposer un _pull request_ qui aura pour effet de construire le programme d’installation d’une disposition contenant vos changement.

Si vous n’êtes pas en mesure de faire ces opérations, n’hésitez pas à me partager vos idées. Je peux dégager un peu de temps pour accommoder certaines modifications (qui resteront non officielles) si cela peu vous aider.

Dans l’un ou l’autre cas, n’hésitez pas à échanger dans les commentaires 🙏

**Comment by d0ob** [comment]
Bonjour, 

Merci pour votre réponse et d’autant plus pour votre proposition ! C’est vraiment aimable, et très apprécié !
Non effectivement je n’aurais pas su où commencer ^^ Mes capacités se sont limitées à utiliser Keyboard Layout Creator, tel que suggéré par Windows ; Et même ça ne fut pas sans déboire, donc ^^ Mais, malgré un moyen un peu barbare, j’aurai finalement pu aboutir sur un résultat tout à fait satisfaisant pour mon usage ! C’était juste histoire de quelques petites modifications très personnelles, et moins indispensables que simplement confortables. Il ne me reste plus qu’à réimprimer des étiquettes mises à jour ! =)

Merci encore !
Bien cordialement, bonne continuation.
