### ISSUE TITLE
Greek characters map

### ISSUE THREAD

**Issue by Slion** [springcomp/optimized-azerty-win#112]
Is the map of Greek characters published somewhere?
The one from [Norme AZERTY](https://norme-azerty.fr) is apparently not complete and sometimes differs from this implementation.

**Comment by springcomp** [comment]
There is an official document that lists the normative list.
However, this is a paid document so I could not have access to it.

That @cyril-L had access to a copy of this document and we had extensive back and forth discussions.
He has created [his implementation](https://github.com/cyril-L/french-nf-azerty-mac) for MacOS based on this official document.

I’m pretty confident this implementation is correct.

It also aligns nicely with the one from [popular Linux distributions](https://github.com/Djyp/azerty_afnor/issues/20).

**Comment by Slion** [comment]
> There is an official document that lists the normative characters.

I saw [that](https://www.boutique.afnor.org/fr-fr/norme/nf-z71300/interfaces-utilisateurs-dispositions-de-clavier-bureautique-francais/fa188960/1792) yes, that's complete nonsense.
