### ISSUE TITLE
Keyboard stickers

### ISSUE THREAD

**Issue by Slion** [springcomp/optimized-azerty-win#113]
What kind of stickers are you using to convert your keyboards?

I used the ones from [TastaturAufkleber.eu](https://www.tastaturaufkleber.eu/Tastaturaufkleber/Tastaturaufkleber-PC/Franzoesisch/Tastaturaufkleber-Franzoesisch-AZERTY-ameliore::286.html) but they deteriorate pretty fast. I first tried their version for laptops that are suppose to work with backlite keyboards. They are basically made of a white material with some black ink on it. The result is that in a matter of weeks the black print fades and the keys you often use whiten little by little. Then I explained them my problem and asked them to produce a set without backlight support. That's basically some black material on which they print the white characters. Sure enough, after a few weeks the white characters were fading away. So while tastaturaufkleber is ok to get started it's not a lasting solution, I can't recommend them unless you absolutely need those stickers fast.

Right now I'm experimenting with custom made stickers I print using a Brother P-touch CUBE Plus in the hope they won't fade since they are laminated labels. Only time will tell though. It's somewhat time consuming but since you print your own you can actually customize your labels, I'm planning to display the Greek letters layer.

![image](https://user-images.githubusercontent.com/6508892/157910419-8449ce72-4030-485b-b22f-a807a68f50c8.png)

**Comment by springcomp** [comment]
That is a really good idea !
Maybe you could share tips and pictures that I could include in the Wiki pages of this repository. Or you could submit those tips to the somewhat official [norme AZERTY](http://norme-azerty.fr) web site.

I actually do not use stickers but use an [LDLC keyboard](https://www.ldlc.com/fiche/PB00279741.html) with the official layout for the office. 

I also designed a [custom layout](https://github.com/springcomp/wasd-iso-104-fr/blob/nf-z71-300/wasd-inkscape-105.88-iso.nf-z71-300.svg) for my [WASD](www.wasdkeyboards.com) mechanical keyboard for use at home.

Finally, I use a Surface Pro 6 Laptop with its built-in cover but that does not prevent me from enjoying the layout as I can pretty much type blindly with muscle memory.

**Comment by Slion** [comment]
I guess having a Wiki page about stickers make sense. You could add me as collaborator in the repo or enable anyone to edit the Wiki.

I could also put the prints documents in your repository if you want. It could be a while until the whole layout it complete though. So far I only did the keys I needed to replace the ones that were badly damaged. Also wanted to first test those TZe label tape.
