### ISSUE TITLE
Subscript and superscript letters

### ISSUE THREAD

**Issue by Slion** [springcomp/optimized-azerty-win#115]
Is there a way to get some of the subscript and superscript letters. I tried with the dead keys I use for numbers against the X but all I got was: ^x ˇx so here clearly we could use that to get sub/superscript.
With N it's more complicated I guess cause one of them is a valid letter apparently: ^n ň
Though I guess we could make a scientific version of the layout that prioritize sub/superscript over rarely used letters such as ň.

**Comment by springcomp** [comment]
Hi @Slion,

The standard mandates that numbers be available using superscript and subscript.
I have [taken the liberty](https://springcomp.github.io/optimized-azerty-win/#fractions) to add `(`, `)`, `+`, `-` and `=` which unlocks a lot of scientific scenarios.

I understand you would like _subscript n_ and _superscript n_ as well.
Those characters do [exist indeed](https://util.unicode.org/UnicodeJsps/character.jsp?a=2099&B1=Show).
- ` ⁿ` U+207F SUPERSCRIPT LATTIN SMALL LETTER N
- `ₙ` U+2099 LATIN SUBSCRIPT SMALL LETTER N

I see no reasons why they could not be supported.
That is a good idea I think.

**Comment by Slion** [comment]
X is definitely available for both. Main main interest was about X

**Comment by springcomp** [comment]
> X is definitely available for both. My main interest was about X.

Then I think it's a good idea. 🙂
Give me a week or so.

**Comment by springcomp** [comment]
@Slion Please, download and try the [latest artifact](https://ci.appveyor.com/api/buildjobs/75e3asj31002d0sm/artifacts/artifacts%2Fsetup.zip) from the continuous build.
This will be valid for a couple of weeks.

It passes the compliance tests and include your suggestions:

- <kbd>^</kbd>, <kbd>x</kbd> outputs `ˣ` (U+02E3 MODIFIER LETTER SMALL X)
- <kbd>Shift</kbd>+<kbd>ˇ</kbd>, <kbd>x</kbd> outputs `ₓ` (U+2093 LATIN SUBSCRIPT SMALL LETTER X)

If you enjoy typing `aˣ + lnₓ(π/₂)` then, let me know 😁.
I’ll publish a new release after a bit of testing.

**Comment by springcomp** [comment]
Implemented in [Release 1.8.0.0](https://github.com/springcomp/optimized-azerty-win/releases/tag/v1.8.0.0).
