### ISSUE TITLE
Got tired of stickers

### ISSUE THREAD

**Issue by Slion** [springcomp/optimized-azerty-win#128]
Here is an early preview of a next gen keyboard I've been working on.
I'm hoping it will be released in the coming weeks.
At this stage this is a reveal exclusive for this community:
![image](https://user-images.githubusercontent.com/6508892/227797835-05ceec27-b84b-4f01-9de1-ece0fc18cb31.png)

**Comment by springcomp** [comment]
Is this a second screen that acts as a keyboard? 🤯

**Comment by Slion** [comment]
It's a Bluetooth keyboard.

**Comment by Slion** [comment]
You should be able to pre-register for it there:
https://play.google.com/store/apps/details?id=net.slions.interface.google

**Comment by Slion** [comment]
I've been using exclusively this keyboard for over year and there is no going back for me now. It's that good. Still the app could be further improved and hopefully it will give enough time.
