### ISSUE TITLE
Problème avec Windows 11

### ISSUE THREAD

**Issue by Aymkdn** [springcomp/optimized-azerty-win#131]
Bonjour,

J'ai deux ordinateurs : 
  - Un perso avec Windows 11 (22621.2861) sur lequel j'ai la version 1.7 du keyboard et qui fonctionne très bien
  - Un pro avec Windows 11 (22000.2652) sur lequel j'ai essayé la version 1.8, puis la version 1.7, mais je n'arrive pas à le faire fonctionner...

Auparavant j'avais Windows 10 sur l'ordi pro et le keyboard layout fonctionnait, mais j'ai migré aujourd'hui sur Windows 11 (après un erase du disque dur). J'arrive à installer le keyboard layout, et il apparait de partout où il devrait. Exemple : 
![image](https://github.com/springcomp/optimized-azerty-win/assets/946315/e9f78965-531e-491a-adf5-1a6521a4e42c)

Je peux l'ajouter dans les langages, etc, mais quoi que je fasse, il n'apparait pas dans la "language bar" (quand je clique en bas à droite sur "FRA", le clavier AZERTY NF Z71-300 n'est pas listé).
![image](https://github.com/springcomp/optimized-azerty-win/assets/946315/4b2754af-b333-4fc7-bb95-27514dcfbfc0)

Quand je suis dans les paramètres avancés du clavier, il est bien listé : 
![image](https://github.com/springcomp/optimized-azerty-win/assets/946315/d1b9ec7e-8cdd-45da-ba21-821e69c7c807)

Mais quand je le sélectionne, rien ne se passe.

J'ai également essayé de le mettre sur un "key sequence" mais pareil, aucun effet : 
![image](https://github.com/springcomp/optimized-azerty-win/assets/946315/ff45b288-5012-4ad4-8baf-c2029505a939)

J'ai essayé de supprimer tous les claviers sauf celui-là, mais il me passe alors sur le QWERTY US…

J'ai essayé de redémarrer plein de fois et de désinstaller/réinstaller, sans succès.

Je suis à court d'idées. Des solutions ?

**Comment by Aymkdn** [comment]
C'est bon j'ai trouvé le problème !

En fait, le fichier `KBFRZ71.dll` n'avait pas été copié dans `C:\Windows\System32`. J'ai récupéré celui de mon ordi perso et je l'ai copié sur le pro, puis après un reboot je peux enfin l'utiliser !

**Comment by springcomp** [comment]
Merci du retour.
Avez-vous par hasard le fichier log d‘installation ?
Cela me permettrait de diagnostiquer l‘installation.

**Comment by Aymkdn** [comment]
Où puis-je le trouver ?

**Comment by springcomp** [comment]
@Aymkdn
Je vous prie de m’excuser pour ma réponse tardive.
L’activation de l’émission des journaux d’installation est un peu compliquée donc je vais prendre sur moi de reproduire l’anomalie.
Merci de votre intérêt pour la disposition.

**Comment by Aymkdn** [comment]
Pas de problème :-)

Pour info, je n'ai pas de droits administrateurs complets sur mon PC pro. C'est sûrement la raison pour laquelle le fichier ne s'est pas copié directement. Grâce à des droits admin restreints, j'ai pu le copier manuellement.  Pas sûr qu'il y ait une solution simple pour cela… mais au moins cet _issue_ pourra en aider d'autres !

**Comment by springcomp** [comment]
Ah oui, il est effectivement nécessaire de disposer des droits d’administration pour installer la disposition.
Mon expérience montre qu’il est assez facile de se faire accompagner par les équipes d’administration si on leur explique qu’il s’agit tout simplement d’une disposition de clavier.
