### ISSUE TITLE
Consider publishing a strictly compliant layout

### ISSUE THREAD

**Issue by springcomp** [springcomp/optimized-azerty-win#55]
While useful and even welcome, the SGCaps feature of the AZERTY-NF layout contradicts the standard that mandates to make the numbers `0` to `9` available directly when using <kbd>Caps Lock</kbd>.

This issue tracks what most users want. Please cast your vote.

[![](https://api.gh-polls.com/poll/01DCFTR7NF434N18SSMA4TQJ9K/Need%20a%20strictly%20compliant%20layout%2C%20unfortunately%20without%20SGCpas)](https://api.gh-polls.com/poll/01DCFTR7NF434N18SSMA4TQJ9K/Need%20a%20strictly%20compliant%20layout%2C%20unfortunately%20without%20SGCpas/vote)
[![](https://api.gh-polls.com/poll/01DCFTR7NF434N18SSMA4TQJ9K/Loosely%20following%20the%20standard%20is%20OK%20as%20long%20as%20SGCaps%20is%20available)](https://api.gh-polls.com/poll/01DCFTR7NF434N18SSMA4TQJ9K/Loosely%20following%20the%20standard%20is%20OK%20as%20long%20as%20SGCaps%20is%20available/vote)

**Comment by tbolon** [comment]
I am torn about this... On one side, I enjoy being able to being able to type with <kbd>Caps Lock</kbd> and easily type special characters (I discovered the SGCaps feature with this driver) but I would love to stick with the standard.

Mays the most obvious should be to release two versions of the driver ? But it will make the development harder (two files, or a build step to merge files together), and something to explain for new users...

If we can find a way to not make it more difficult for daily development/contributions AND find a clear explanation on the website, perhaps we should build two separate drivers ?

**Comment by springcomp** [comment]
Thank you for your feedback.

I’m OK to build two drivers and promote the standard-compliant one on the documentation page.

The standard authorizes variations as long as one does not claim standard compliance. So we could have a paragraph to advertise that the choice is available for advanced users.

I think I will delay working on this, though, to wait for this project to gain a bit more visibility and let the community have a chance to know and participate to this poll :-)

**Comment by thibthib17** [comment]
I agree it would be nice to have both. Personally, I find SGCaps better on desktop when you have a numeric keypad but NF Z71-300 standard is far better for mobile computers where you don't have a numeric keypad. The standard needed to be compliant and usable for all users, therefore the consensus in the WG was to disable SGCaps, in order to be compliant to mobile computers user's needs.

Best,

TG
