### ISSUE TITLE
Provide a non-admin distribution with Portable Keyboard Layout (PKL)

### ISSUE THREAD

**Issue by nagromc** [springcomp/optimized-azerty-win#77]
[Portable Keyboard Layout (PKL)](https://github.com/Portable-Keyboard-Layout/Portable-Keyboard-Layout) provides a way to use a different keyboard layout without the need of administrator permissions.

For those who cannot install softwares at work, it could be great to have a non-admin distribution relying on PKL.

For your information, [bepo.fr](http://bepo.fr/wiki/Portable_Keyboard_Layout) provides their own bépo distribution using this software.

**Comment by springcomp** [comment]
Thank you very much for your interest.
I may consider doing this.
Doesn't the competing [PKL Afnor](https://sourceforge.net/projects/francaisnormaliseazerty/files/) from Gilbert Galéron fit your requirements though?

**Comment by nagromc** [comment]
Nice catch! I didn't know about this distribution. Well, I‘m not an NF Z71-300 expert, but so far, it seams to do the job.
