### ISSUE TITLE
Unable to install due to missing files in installation folder?

### ISSUE THREAD

**Issue by ClavierPixelKey** [springcomp/optimized-azerty-win#91]
I think the installation folder should have the following folders:
amd64 
i386 
ia64 
wow64

I tried to go to the LDLC Azerty+ website and their setup file (which is the same as yours) has the same problem

**Comment by springcomp** [comment]
Can you explain the steps that lead to your problem?
Have you tried using the quick PowerShell script in the TL;DR section from [the download page](https://springcomp.github.io/optimized-azerty-win/download.html) ?

**Comment by springcomp** [comment]
I believe you might be on a platform I have not tested yet.
Can you clarify which exact version of Windows your are running?

**Comment by ClavierPixelKey** [comment]
My HP Spectre x360 is running Windows 10 Home build 1809 while my Asus N55SF is running Windows 10 Home build 1903.

The setup file doesn’t work on either machine.

**Comment by ClavierPixelKey** [comment]
I think the reason is because the .DLL files are missing in the latest version.

**Comment by ClavierPixelKey** [comment]
I downloaded setup file v1.0.0.0 and the missing folders are there:
amd64
i386
ia64
wow64

![installation_01](https://user-images.githubusercontent.com/35109247/70406553-1d6a6400-1a7c-11ea-92f3-640e36955b6d.PNG)

**Comment by springcomp** [comment]
Thanks for the feedback.

Based on the missing folders, could you try to identify which of the two missing folders is required on your system?

Starting with the v1.0.0.0 installation, you could remove a folder one by one to know when installation breaks.

Thank you for your time.

**Comment by ClavierPixelKey** [comment]
amd64
i386
ia64
wow64

KBFRZ71_amd64.msi
KBFRZ71_i386.msi
KBFRZ71_ia64.msi
setup.exe

Actually, all of these folders and files should be in the installation folder.

I use [Microsoft Keyboard Layout Creator](https://www.microsoft.com/en-us/download/details.aspx?id=22339) (MSKLC). When I create a new setup file using the KBFRZ71.klc source code, all of those folders and files — except Setup.exe.config — are automatically generated by the program.  

![MSKLC_01](https://user-images.githubusercontent.com/35109247/70417621-a4c7cf80-1a9c-11ea-9108-56853543214f.PNG)

![MSKLC_02](https://user-images.githubusercontent.com/35109247/70417635-a98c8380-1a9c-11ea-9456-92c42abaeaea.PNG)

In MSKLC I had to rename the keyboard name to a different name that states the version number (V170) before “Build DLL and Setup Package” to avoid the error below:

 ERROR: The keyboard name 'KBFRZ71' is already in use on this machine.

**Comment by springcomp** [comment]
I’m not sure I understand your issue.

Please, be aware that I __do not__ provide the automatically generated files from MSKLC.
Instead, I provide the following files that I carefully created from the source code in this repository:
- KBFRZ71_i386.msi : x86 version of the keyboard layouts installation package.
- KBFRZ71_amd64.msi : x64 version of the keyboard layouts installation package.
- Setup.exe : a custom setup program that detects the OS version and launches either the x86 or x64 variants of the msi files above.

Those files are not identical to the ones that would be automatically generated by MSKLC.
Indeed, MSKLC is not able to produce installation packages that contain _two_ different keyboard layout DLLs.

Whereas, my installation packages contain both the `KBFRZ71.DLL` and `KBFRZ71N.DLL` corresponding to the `AZERTY NF Z71-300` and `AZERTY NF Z71-300 (Numérique)` drivers respectively.

As far as I’m aware, MSKLC would generate four installation packages, for different CPU architectures.
- i386 : targetting x86.
- amd64 : targetting x64.
- ia64 : targetting Itanium architecture (obsolete).
- wow64 : targetting windows 32 bits on Windows x86.

The Itanium architecture is obsolete, and therefore, there is no need to provide an installation package for this architecture.

The Wow64 architecture is actually the Windows 32 bits substystem, running on Windows x64. My experience is that legacy x86 programs running on Windows x64 run perfectly well with my keyboard layout. Therefore, I do not need to provide this installation package.

Now, is there an issue you are facing that prevents you from installing and or using my keyboard layout?
Please, can you share the text or a screenshot of the error you are facing?
Or can you share the name and version of a program that does not work properly with the keyboard layout?

I would be more than happy to assist you further.

**Comment by springcomp** [comment]
Please, be aware that the `KBFRZ71.klc` and `KBFRZ71N.klc` files provided in this repository __should not__ be used with the main MSKLC program.

They can be opened successfully by MSKLC.
However, if you generate keyboard layouts from MSKLC, you will generate buggy drivers, because MSKLC does not preserve the order in which the layout is declared.

Specifically, you’ll observe that, to prevent some bugs, some keys must be declared last in the layout file but MSKLC does not preserve this order and generates faulty DLLs.

Please, see issue #74 for more details.

**Comment by springcomp** [comment]
And finally, before installing a newer version of the layout, you must first uninstall any previous versions.
I will add a FAQ to clarify this point.

**Comment by ClavierPixelKey** [comment]
installation_00](https://user-images.githubusercontent.com/35109247/70447574-e2971900-1ad9-11ea-98a5-6451aa7f7421.PNG)

Ah it works after I uninstalled it and then signed out and logged in back to Windows. The problem was that I already had the previous version (1.3.0.0) which needed to be uninstalled first before installing a another version.

It just feels weird because there's no "successful installation" dialog box. And there's no "keyboard already installed" error...



installation_03](https://user-images.githubusercontent.com/35109247/70447781-4ae5fa80-1ada-11ea-825d-67d837cbe1af.png)

(This dialog also disappears immediately afterwards, making me think the keyboard is not installed properly.)

... unlike the one compiled with MSKLC

installation_04_compiledwithMSKLC](https://user-images.githubusercontent.com/35109247/70447811-5b967080-1ada-11ea-98b4-4405934143cc.PNG)

**Comment by springcomp** [comment]
Ok cool!

So I need better doc and hopefully improved checks in the Setup program.

Thanks for clarifying.
Please feel free to close this issue if you don't have other requests to make / information to add.

**Comment by ClavierPixelKey** [comment]
OK everything is installed. :)

By the way, what does NF Z71-300 stand for?

**Comment by springcomp** [comment]
> By the way, what does NF Z71-300 stand for?

I have no idea.
It must be part of the numbering system used by AFNOR.
Here is [the link](https://www.boutique.afnor.org/norme/nf-z71-300/interfaces-utilisateurs-dispositions-de-clavier-bureautique-francais/article/901594/fa188960) to the standard.
