### ISSUE TITLE
Not compatible with ALT+X feature in Microsoft Word (wait, it’s not an issue)

### ISSUE THREAD

**Issue by ClavierPixelKey** [springcomp/optimized-azerty-win#93]
In Microsoft Word, there is a little-known feature that automatically converts Unicode code points.

For example, in MS Word, type 0153 and then press ALT+X to get “œ”. Press ALT again to get back 0153

Unfortunately this won’t work if the keyboard layout has a character already defined at ALT+X

Wait, apparently this Microsoft Word only works for the standard US ANSI keyboard layout which treats the ALTGR key as ALT

So this is not an issue. Please close this. :)

**Comment by springcomp** [comment]
You can close it yourselves !
