### ISSUE TITLE
Add FAQ clarifying how to install a newer version of the layout

### ISSUE THREAD

**Issue by springcomp** [springcomp/optimized-azerty-win#94]
TL;DR
- Unregister the layout from the language bar.
- Uninstall the layout from add/remove programs.
- Disconnect from Windows.
- After logging in again, install the new version.
- You might need to disconnect and login yet another time for changes to take effect.

**Comment by patraf1** [comment]
If you have Windows Defender active, you may see this window appearing when you try to install the new driver
![defender1](https://user-images.githubusercontent.com/58404965/70637315-ee482400-1c2e-11ea-9eb3-1c8a1417b154.JPG)
You must then click on "further information" (or its equivalent in other languages), you will get a new window 
![defender2](https://user-images.githubusercontent.com/58404965/70637415-1899e180-1c2f-11ea-81cf-db0832e713f0.JPG)
and you have to click on "execute anyway" (or its equivalent)

**Comment by patraf1** [comment]
Every time I use the lock screen (Windows+L) I get back to the standard AZERTY driver.
What did I do wrong?

**Comment by springcomp** [comment]
> If you have Windows Defender active, you may see this window appearing when you try to install the new driver (...)
> You must then click on "further information" (or its equivalent in other languages), you will get a new window (...)
> and you have to click on "execute anyway" (or its equivalent)

Thanks, I’ll take this into account when writing the doc.
