### ISSUE TITLE
After unlocking the workstation, the standard AZERTY driver is reset as default

### ISSUE THREAD

**Issue by springcomp** [springcomp/optimized-azerty-win#95]
Migrated from #94 - @patraf1.
Every time I use the lock screen (Windows+L) I get back to the standard AZERTY driver.
What did I do wrong?

**Comment by ClavierPixelKey** [comment]
Have you made sure that the AZERTY-NF is at the top of the list of input methods?

**Comment by patraf1** [comment]
Yes, it works!

 

Seems that there is no menu to go to this parameter with Windows 10 1809.

Type “input” (saisie) in the Parameter window, go to Advanced keyboard parameters (paramètres avancés de clavier).

 

Thanks,

Patrick Raffin

 

De : Lennert <notifications@github.com> 
Envoyé : jeudi 12 décembre 2019 14:54
À : springcomp/optimized-azerty-win <optimized-azerty-win@noreply.github.com>
Cc : patraf1 <patrick@raffin.email>; Mention <mention@noreply.github.com>
Objet : Re: [springcomp/optimized-azerty-win] After unlocking the workstation, the standard AZERTY driver is reset as default (#95)

 

Have you made sure that the AZERTY-NF is at the top of the list of input methods?
