### ISSUE TITLE
Windows language setting switching w/o WIN+Space being used

### ISSUE THREAD

**Issue by Danilodambre** [springcomp/optimized-azerty-win#98]
Hello.

I’ve been using LDLC’s Azerty+ for 2 weeks, and every 5 minutes or so, the language setting reverts back to the usual Azerty one. This happens in both ways (Azerty to +). I’m mainly using DeepL plugin for Windows, maybe it sends the WIN+Space signal by itself?

Any idea is welcome.

(Windows 10 on an acer laptop)

**Comment by springcomp** [comment]
Thanks your feedback.
I'm sorry you are having troubles.
By any chance would this happen also with other layouts or only the new AZERTY+ layout?

Please, can you share which version of Windows you are running on?
An [which version](https://github.com/springcomp/optimized-azerty-win/wiki/FAQ#which-version)     of the layout?

**Comment by Danilodambre** [comment]
Thanks for the quick reply. 

I’m only switching between Windows FRA default layout and FRA Azerty NF layout installed from LDLC file,

I’m under Windows 10 17134.1069, and layout installed comes from the file LDLC_BW10_Z71-300.zip, which installed version 1.3.0.0

**Comment by ClavierPixelKey** [comment]
Make sure you leave this unchecked: “Let me set a different input method for each app window”, especially if the default Windows FRA layout is configured to be at the top of the list of input methods for your PC. It is also a good idea to disable shortcuts for quick access to different input methods. Once, I accidentally switched layouts mid-game, and as I was learning Bépo at that time, I couldn’t move ↑←↓→ at all! 😱

Settings ⇨ Time & Language ⇨ Language ⇨ Spelling, typing, & keyboard settings _(on the right)_ ⇨ _(scroll all the way down)_ ⇨ Advanced keyboard settings

![Advanced keyboard settings_Win10](https://user-images.githubusercontent.com/35109247/70865990-dcec7800-1f9e-11ea-84ca-dac56271cd45.PNG)

**Comment by Danilodambre** [comment]
I’ve removed everything as asked, and… it seems to work!

Thanks a lot, you’re making this a lot more comfortable ! (by the way I bought the keyboard because of your post on Mastodon, so thanks for hat too!

**Comment by springcomp** [comment]
@ClavierPixelKey Thanks for your help.
@Danilodambre Glad your problem is solved.

Would you mind sharing the URL to the post on Mastodon. I don’t use it so I’m curious to read the post. 😃

**Comment by ClavierPixelKey** [comment]
🙂

I have no idea about the post on Mastodon...?

**Comment by Danilodambre** [comment]
Well… Color me surprised.
The toot here : https://toot.plus.yt/@Djyp/103194822332503216
Says that @Djyp is proud that LDLC is linking his repo. Maybe I missed something?

**Comment by springcomp** [comment]
> Says that @Djyp is proud that LDLC is linking his repo. Maybe I missed something?

No worries.

LDLC linked mentioned my name and linked to this repo, as well as providing a direct download of an earlier version of this driver.

LDLC also briefly linked to @Djyp and @cyril-L who made the Linux and Mac versions respectively.

Everybody wins 👏
