### ISSUE TITLE
< and > are inverted

### ISSUE THREAD

**Issue by 240-185** [springcomp/optimized-azerty-win#99]
Hello, it's me again :3

It appears that < and > are inverted, and is a bit confusing when using LDLC's keyboard.

[EDIT] To be closed, it's actually LDLC who f*d up

**Comment by ClavierPixelKey** [comment]
Wow that's funny. I don't think it's possible to take out the key and rotate it. Maybe you can buy some AZERTY amélioré stickers from the German website?

**Comment by 240-185** [comment]
Even if it were possible, rotating the key would be pointless; the signs would still be in the same position. Cue the sad trumpet.

Either it's possible to buy some stickers in order to cover this mistake, either it's possible to contact LDLC who will send a new keycap that will replace the former.

**Comment by springcomp** [comment]
Indeed, good catch.

LDLC will provide a new key to anyone willing to receive one.
Presumably, with a proof of purchase.

I received mine a few days ago.
I must admit I did not identify this mistake and it is not really disturbing for day to day usage.

**Comment by xDEADC0DE** [comment]
> Hello, it's me again :3
> 
> It appears that < and > are inverted, and is a bit confusing when using LDLC's keyboard.
> 
> [EDIT] To be closed, it's actually LDLC who f*d up

I noticed the same issue on the LDLC keyboard ^^;; I don‘t want to throw to much shade on them, it’s nice to have at least one keyboard with the new layout.
… stil, #YouHadOneJob ^^;;;

I didn’t know they sent a replacement key, thanks for the tip!
